//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Araba_Takip
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracTanimlamas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AracTanimlamas()
        {
            this.AracIslemleris = new HashSet<AracIslemleris>();
            this.BakimOnarims = new HashSet<BakimOnarims>();
            this.SurucuDetays = new HashSet<SurucuDetays>();
        }
    
        public int AracId { get; set; }
        public string Arac_Plakasi { get; set; }
        public string Firma_arac_no { get; set; }
        public string Arac_markasi { get; set; }
        public string Arac_modeli { get; set; }
        public string Model_yili { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AracIslemleris> AracIslemleris { get; set; }
        public virtual AracTanimlamas AracTanimlamas1 { get; set; }
        public virtual AracTanimlamas AracTanimlamas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BakimOnarims> BakimOnarims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurucuDetays> SurucuDetays { get; set; }
    }
}
