//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Araba_Takip
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracIslemleris
    {
        public int Arac_isId { get; set; }
        public int AracId { get; set; }
        public string Sigorta_islemleri { get; set; }
        public string Ceza_islemleri { get; set; }
        public string Kaza_islemleri { get; set; }
        public string Arac_muayeneleri { get; set; }
        public string OGS_HGS_giderleri { get; set; }
    
        public virtual AracTanimlamas AracTanimlamas { get; set; }
    }
}
