//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Araba_Takip
{
    using System;
    using System.Collections.Generic;
    
    public partial class BakimOnarims
    {
        public int Bakim_Id { get; set; }
        public Nullable<int> AracId { get; set; }
        public string Bakim_tarihi { get; set; }
        public string Bakim_KMsi { get; set; }
        public string Tutar { get; set; }
        public string Firma_servis { get; set; }
        public string Aciklamalar { get; set; }
    
        public virtual AracTanimlamas AracTanimlamas { get; set; }
    }
}
