//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Araba_Takip
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurucuDetays
    {
        public int SurucuId { get; set; }
        public Nullable<int> AracId { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Tel { get; set; }
        public string Adres { get; set; }
        public string Ehliyet { get; set; }
    
        public virtual AracTanimlamas AracTanimlamas { get; set; }
    }
}
